version: "3"

services:
  minecraft-example:
    container_name: minecraft-example
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      #Required
      EULA: "TRUE"
      #Server Settings
      SERVER_PORT: 25565 #DO NOT CHANGE
      TYPE: "FOLIA"
      # VERSION: "1.20.0"
      SERVER_NAME: "minecraft-example"
      MOTD: ""
      DIFFICULTY: "normal"
      MODE: "survival"
      MAX_PLAYERS: 10
      MAX_WORLD_SIZE: 1000000 #Expressed as a radius (1 Million)
      PVP: TRUE
      #Performance
      VIEW_DISTANCE: 32
      SIMULATION_DISTANCE: 32 #Should match VIEW_DISTANCE.
      MEMORY: 1G #Defaults to 1G.
      MAX_MEMORY: 8G #8G
      PLAYER_IDLE_TIMEOUT: 600
      #AutoPause
      ENABLE_AUTOPAUSE: false
      AUTOPAUSE_KNOCK_INTERFACE: "eth0"
      DEBUG_AUTOPAUSE: false
      #Whitelist
      ENABLE_WHITELIST: TRUE
      WHITELIST: '' #A list of usernames and/or UUIDs separated by commas.
      #Misc
      SNOOPER_ENABLED: false
      MAX_TICK_TIME: 60000 #Must be set to -1 or really high if AutoPause is enabled.

    tty: TRUE
    stdin_open: TRUE
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data #Must use an absolute source path for TrueNAS Scale.
